---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  commands:
  - echo hello world
  - echo hello world 2
- name: test docker
  environment:
    PASSWORD:
      from_secret: SCAN_PASS
    USERNAME:
      from_secret: SCAN_USER
  commands:
  - docker pull zookeeper:latest
  - docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock registry.aquasec.com/scanner:2022.4 scan -H https://8f9482d77b.cloud.aquasec.com/ -U $USERNAME -P $PASSWORD --local zookeeper:latest
...
