---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  commands:
  - echo hello world
  - echo hello world 2
- name: test docker
  environment:
    PASSWORD:
      from_secret: AQUA_DEMO_PASS
    USERNAME:
      from_secret: AQUA_DEMO_USER
  commands:
  - docker images
  - docker pull zookeeper:latest
  - docker pull hello-world
  - docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock registry.aquasec.com/scanner:2022.4 \ 
    scan --no-verify -H http://aquasec-demo3581-vm0.eastus.cloudapp.azure.com/ -U $USERNAME -P $PASSWORD --local hello-world:latest

