version: 2
jobs:
  build:
    environment:
      IMAGE_NAME: graphql-circleci
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Aqua Scan
          command:  |
                    export AQUA_KEY=$AQUA_KEY
                    export AQUA_SECRET=$AQUA_SECRET
                    export trivyVersion=0.31.2
                    export TRIVY_RUN_AS_PLUGIN=aqua
                    curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b . v${trivyVersion}
                    ./trivy fs --security-checks config,vuln,secret .
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:latest .
  publish-latest:
    environment:
      IMAGE_NAME: graphql-circleci
    steps:
      - setup_remote_docker
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - master 
                - circleci-project-setup
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: 
                - master 
                - circleci-project-setup
